#!/usr/bin/env python3
"""Regenerate REQUIRED_LINKS in validate-distribution.py from the current skill tree.

The validator must assert a FROZEN set: deriving links at runtime would make deleting one
invisible, which is the whole failure being guarded against. So the set is generated here,
deliberately, and committed. Run this after intentionally adding or removing a cross-skill link,
and the diff shows exactly which links changed.

Frontmatter is stripped on purpose. A `description:` is trigger text the runtime shows the model to
decide *whether* to invoke a skill; it is never an instruction the model follows. A cross-skill
reference there would be decoration, so counting it as an enforced link would freeze a link that
does no work. Instructions live in the body, and so do the links worth protecting.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

HEADER = (
    "# Every cross-skill link present in the tree, generated by\n"
    "# `scripts/render-required-links.py` and asserted thereafter. Curating a subset invited three\n"
    "# rounds of \"your list is incomplete\"; the complete set makes deletion of ANY link explicit.\n"
)


def collect(root: Path) -> dict[str, list[str]]:
    skills = root / "skills"
    names = {d.name for d in skills.iterdir() if (d / "SKILL.md").exists()}
    links: dict[str, list[str]] = {}
    for d in sorted(skills.iterdir()):
        skill = d / "SKILL.md"
        if not skill.exists():
            continue
        body = re.sub(r"^---\n.*?\n---\n", "", skill.read_text(), flags=re.S)
        found = sorted(
            {r for r in re.findall(r"`[$/]?(nuclear-[a-z-]+)`", body) if r in names and r != d.name}
        )
        if found:
            links[d.name] = found
    return links


def render(links: dict[str, list[str]]) -> str:
    rows = "\n".join(
        f'    "{k}": {{' + ", ".join(f'"{x}"' for x in v) + "}," for k, v in links.items()
    )
    return f"{HEADER}REQUIRED_LINKS = {{\n{rows}\n}}"


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    target = root / "scripts" / "validate-distribution.py"
    text = target.read_text()
    pattern = re.compile(r"# Every cross-skill link present.*?\nREQUIRED_LINKS = \{.*?\n\}", re.S)
    if not pattern.search(text):
        print("REQUIRED_LINKS block not found in validate-distribution.py", file=sys.stderr)
        return 1
    links = collect(root)
    updated = pattern.sub(lambda _: render(links), text)
    if updated == text:
        print(f"REQUIRED_LINKS already current ({sum(len(v) for v in links.values())} links)")
        return 0
    target.write_text(updated)
    print(f"wrote REQUIRED_LINKS: {sum(len(v) for v in links.values())} links across {len(links)} skills")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
